---
title: "COMPASS Synoptic Discrete Data Workflow: Example Worflow"
author: "Stephanie J. Wilson & Stephanie Pennington"
date: '2024-10-08'
output: html_document
---
##Setup
```{r setup, include=FALSE}

#let you know which section you are in 
cat("Setup")

#a link to the Gitbook or whatever protocol you are using for this analysis 


#Packages that are required 
  library(dplyr)
  library(ggplot2)
  library(ggpubr)
  library(stringr)

#any coefficients / constants that are needed for calculations 


#expected ranges for sample concentrations used for flags 
  # min_conc = int
  # max_conc = int
  # cv_flag = 10% 
  # rep_flag = 10%

#check standard concentrations 
  # chk_std = 10
  

#any reference to other code 



```

## Import Data  
```{r Import Data, echo=FALSE}
cat("Import Data")

#set working directory
  #could be from google drive or local drive etc. 
setwd("file path")

#Read in Raw Data 
raw <- read.csv("raw_datafile.csv")
head(raw)

```

## Assessing standard Curves 
```{r Assess Standard Curves, echo=FALSE}

cat("Assess Standard Curves")

#Identify standards within raw file 


#Plot standard Curve or Curves 


#Pull out slope and R2 


#Report out a flag if the run has an R2 lower than appropriate 


#compare slopes to previous runs (from log) in order to assess drift 


#write out slopes from current run to log 

```

## Sample Processing - Calculating Concentrations  
```{r Sample Processing, echo=FALSE}

cat("Sample Processing")

#Remove standards if necessary 


#Calculate concentrations from standard curve 



##########make flags for any dilutions needed 
#highest CH4 standard = 10000
#highest CO2 standard = 50000

Samples$CH4_Flag <- ifelse(Samples$CH4_Conc_ppm >10000, "Needs Dilution", "Within Range")
Samples$CO2_Flag <- ifelse(Samples$CO2_Conc_ppm >50000, "Needs Dilution", "Within Range")
#head(Samples)

```

## Sample Flagging - Within standards range?  
```{r Sample Processing, echo=FALSE}

cat("Sample Flagging")

#Flagging data if the concentration is outside the standards range 


#Flagging for CV of analytical duplicates or replicates 



```

## Analyze the Check Standards 
```{r Check Standards, echo=FALSE}

cat("Analysis Check Standards")

#Pull out check standards from raw file 


#Calculate their concentrations if not done already 


#change this if check standard concentrations are different 


#calculate percent difference between check standards & expected concentration 


#flag if the percent difference is over X% (defined in setup)


#Visualize check std concentrations vs. the expected concentrations


#report out if flags indicate need for rerun


```

## Dilution Corrections 
```{r Dilution Corrections}

cat("Dilution Corrections")

#Calculate the concentration when accounting for the dilution factor


#check results
#head(Samples)

#quick first look at the samples 
ch4_samples <-  ggplot(data = Samples, aes(x = Sample_ID, y = CH4_Conc_ppm, fill=CH4_Flag)) +
       geom_bar(stat = 'identity') + 
        scale_fill_manual(values=c("red","darkgreen"))+
        #scale_fill_gradient2(low='red', mid='white', high='blue', space='Lab') + 
        theme_classic() + labs(x= " ", y="CH4 (ppm)", title="CH4: Green = Within Range") + 
        theme(legend.position="none") 


co2_samples <-  ggplot(data = Samples, aes(x = Sample_ID, y = CO2_Conc_ppm, fill=CO2_Flag)) +
       geom_bar(stat = 'identity') + 
        scale_fill_manual(values=c("red", "darkgreen"))+
        #scale_fill_gradient2(low='red', mid='white', high='blue', space='Lab') + 
        theme_classic() + labs(x= " ", y="CO2 (ppm)", title="CO2: Green = Within Range") + 
        theme(legend.position="none") 

ggarrange(ch4_samples, co2_samples, nrow=1, ncol=2)


```

## Visualize Data 
```{r Visualize Data}

cat("Visualize Data")

#Plot samples to get a first look at concentrations (sanity check)


```

## Export Processed Data  
```{r, Export Processed Data}

cat("Export Processed Data")

#set working directory 
setwd("filepath")

#Prepare data to be exported 

#Add any necessary identifiers to the samples 
  #example read in sample IDs list and merge 
  #create required ID columns in R, etc. 

#Write out data frame 
write.csv(alldat, "COMPASS_CBSYN_SGW_202311_Processed.csv")

```

#end
